### ISSUE TITLE
Demo doesn't work well on small screens

### ISSUE THREAD

**Issue by skirridsystems** [brunob/leaflet.fullscreen#86]
On mobile screens the page gets rescaled and the button is very small.
https://brunob.github.io/leaflet.fullscreen/

These CSS changes might help.

```css
#container {
  margin: 0 auto;
  max-width: 700px; /* allow container to shrink for small screens */
}

#map {
  width: 100%;  /* fill container width */
  height: 600px;
  border: 1px solid #ccc;
}
```
